-- MySQL Script generated by MySQL Workbench
-- Sat May  7 19:26:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dindinagora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dindinagora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dindinagora` DEFAULT CHARACTER SET utf8 ;
USE `dindinagora` ;

-- -----------------------------------------------------
-- Table `dindinagora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`cliente` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` BIGINT NOT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `data_removido` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `dindinagora`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`endereco` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  `cidade_id` BIGINT NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `cep` INT NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(64) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `data_removido` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_endereco_cidade_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dindinagora`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cidade`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `dindinagora`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`produtos` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `periodo_carencia` DATETIME NOT NULL,
  `valor` DECIMAL(65,2) UNSIGNED NOT NULL DEFAULT 0,
  `data_criacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `data_removido` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`aquisicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`aquisicoes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  `data_aquisicao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_remocao_aquicicao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aquisicoes_produtos_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_aquisicoes_cliente_idx` (`cliente_id` ASC) VISIBLE,
  UNIQUE INDEX `produtos_id_UNIQUE` (`produtos_id` ASC, `cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_aquisicoes_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `dindinagora`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aquisicoes_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dindinagora`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`conta_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`conta_tipo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_criacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `data_removido` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`conta` (
  `id` INT UNSIGNED NOT NULL,
  `conta_tipo_id` BIGINT NOT NULL,
  `cliente_id` BIGINT UNSIGNED NOT NULL,
  `saldo` DECIMAL(65,2) NULL DEFAULT 0,
  `numero_conta` BIGINT UNSIGNED NOT NULL,
  `data_abertura_conta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `data_removido` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conta_conta_tipo_idx` (`conta_tipo_id` ASC) VISIBLE,
  UNIQUE INDEX `saldo_UNIQUE` (`saldo` ASC) VISIBLE,
  INDEX `fk_conta_cliente_idx` (`cliente_id` ASC) VISIBLE,
  UNIQUE INDEX `numero_conta_UNIQUE` (`numero_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_conta_tipo`
    FOREIGN KEY (`conta_tipo_id`)
    REFERENCES `dindinagora`.`conta_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dindinagora`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`tipos_de_transferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`tipos_de_transferencia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `data_criacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`transferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`transferencias` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta_id` INT NOT NULL,
  `tipo_transferencia` INT NOT NULL,
  `valor_transferencia` DECIMAL(65,2) NOT NULL DEFAULT 0,
  `chave_pix` VARCHAR(255) NULL DEFAULT 0,
  `codigo_banco` INT NULL,
  `agencia` VARCHAR(45) NULL,
  `digito` VARCHAR(16) NULL,
  `conta` INT NULL,
  `nome` VARCHAR(200) NULL,
  `identificacao` VARCHAR(255) NULL,
  `data_transferencia` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_transferencias_conta_idx` (`conta_id` ASC) VISIBLE,
  INDEX `fk_transferencias_transferencia_idx` (`tipo_transferencia` ASC) VISIBLE,
  CONSTRAINT `fk_transferencias_conta`
    FOREIGN KEY (`conta_id`)
    REFERENCES `dindinagora`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencias_transferencia`
    FOREIGN KEY (`tipo_transferencia`)
    REFERENCES `dindinagora`.`tipos_de_transferencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindinagora`.`depositos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindinagora`.`depositos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta_id` INT NOT NULL,
  `tipo_transferencia` INT NOT NULL,
  `valor_depositado` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `chave_pix` VARCHAR(255) NULL DEFAULT 0,
  `codigo_banco` INT NULL,
  `agencia` VARCHAR(45) NULL,
  `digito` VARCHAR(16) NULL,
  `conta` INT NULL,
  `nome` VARCHAR(200) NULL,
  `identificacao` VARCHAR(255) NULL,
  `data_deposito` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_transferencias_conta_idx` (`conta_id` ASC) VISIBLE,
  INDEX `fk_transferencias_transferencia_idx` (`tipo_transferencia` ASC) VISIBLE,
  CONSTRAINT `fk_transferencias_conta0`
    FOREIGN KEY (`conta_id`)
    REFERENCES `dindinagora`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencias_transferencia0`
    FOREIGN KEY (`tipo_transferencia`)
    REFERENCES `dindinagora`.`tipos_de_transferencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
