-- MySQL Script generated by MySQL Workbench
-- Fri May  6 16:54:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dindin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dindin` ;

-- -----------------------------------------------------
-- Schema dindin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dindin` DEFAULT CHARACTER SET utf8 ;
USE `dindin` ;

-- -----------------------------------------------------
-- Table `dindin`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`cliente` ;

CREATE TABLE IF NOT EXISTS `dindin`.`cliente` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `cpf` INT NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`cidade` ;

CREATE TABLE IF NOT EXISTS `dindin`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`endereco` ;

CREATE TABLE IF NOT EXISTS `dindin`.`endereco` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  `cidade_id` BIGINT NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `cep` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`conta_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`conta_tipo` ;

CREATE TABLE IF NOT EXISTS `dindin`.`conta_tipo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`conta` ;

CREATE TABLE IF NOT EXISTS `dindin`.`conta` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  `conta_tipo_id` BIGINT NOT NULL,
  `saldo` DECIMAL NULL DEFAULT 0,
  `numero_conta` BIGINT UNSIGNED NOT NULL,
  `data_abertura_conta` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  UNIQUE INDEX `saldo_UNIQUE` (`saldo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`depositos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`depositos` ;

CREATE TABLE IF NOT EXISTS `dindin`.`depositos` (
  `id` BIGINT UNSIGNED NOT NULL,
  `conta_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`produtos` ;

CREATE TABLE IF NOT EXISTS `dindin`.`produtos` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`aquisicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`aquisicoes` ;

CREATE TABLE IF NOT EXISTS `dindin`.`aquisicoes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`transferencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`transferencias` ;

CREATE TABLE IF NOT EXISTS `dindin`.`transferencias` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dindin`.`estado` ;

CREATE TABLE IF NOT EXISTS `dindin`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
